export { authService } from './auth/auth.service'
export { usersService } from './users/users.service'
export { dashboardService } from './dashboard/dashboard.service'
export { tipoReclamoService } from './tipo-reclamo/tipo-reclamo.service'
export { areasService } from './areas/areas.service'
export { reclamosService } from './reclamos/reclamos.service'
export { proyectosService } from './proyectos/proyectos.service'
export * from './endpoints'
